# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tut',
                'doc_host': 'https://sebastianf101.github.io',
                'git_url': 'https://github.com/sebastianf101/nbdev_tut',
                'lib_path': 'nbdev_tut'},
  'syms': {'nbdev_tut.core': {'nbdev_tut.core.foo': ('core.html#foo', 'nbdev_tut/core.py')}}}