# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ejedic.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../nbs/01_ejedic.ipynb 4
def foo(): pass

# %% ../nbs/01_ejedic.ipynb 5
def say_hello(to):
    "Saludar al parámetro"
    return f'Hola querido {to}!'
